# Generated by Django 3.2.3 on 2021-06-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=400)),
                ('tag', models.CharField(max_length=400)),
                ('contest', models.CharField(max_length=10)),
                ('search', models.CharField(max_length=1000)),
            ],
        ),
    ]
